import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

from openpyxl import Workbook


REPO_ROOT = Path("/Users/razzo/Documents/For Codex/sheet-doctor")
HEAL_PATH = REPO_ROOT / "skills" / "csv-doctor" / "scripts" / "heal.py"


def load_module(path: Path, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


class HealEdgeCaseTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.heal = load_module(HEAL_PATH, "sheet_doctor_heal_edge_cases")

    def test_preprocess_rows_uses_last_header_like_row_and_logs_metadata(self):
        rows = [
            ["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""],
            ["Generated by SAP on 15/01/2024", "", "", "", "", "", "", ""],
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
        ]

        trimmed, changes = self.heal.preprocess_rows(rows)

        self.assertEqual(trimmed[0], self.heal.HEADERS)
        self.assertEqual(len(changes), 2)
        self.assertTrue(all(change.column_affected == "[file metadata]" for change in changes))

    def test_preprocess_rows_merges_multirow_header_band(self):
        rows = [
            ["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""],
            ["Employee", "", "Transaction", "", "", "Approval", "", ""],
            ["Name", "Division", "Date", "Cost", "Curr", "State", "Comments", ""],
            ["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "approved", "Taxi", ""],
        ]

        trimmed, changes = self.heal.preprocess_rows(rows)

        self.assertEqual(trimmed[0][0], "Employee Name")
        self.assertEqual(trimmed[0][1], "Employee Division")
        self.assertEqual(trimmed[0][2], "Transaction Date")
        self.assertEqual(trimmed[0][5], "Approval State")
        self.assertTrue(any(change.column_affected == "[header band]" for change in changes))

    def test_formula_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "=SUM(A1:A10)", "USD", "Travel", "Approved", "Carry-over"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 0)
        self.assertEqual(len(quarantine), 1)
        self.assertEqual(quarantine[0].reason, "Excel formula found, not data")
        self.assertTrue(any("formula_residue" in change.reason for change in changelog))

    def test_combined_amount_currency_is_split(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "$1,200 USD", "", "Travel", "Approved", "Taxi"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[0].row[self.heal.COL["Amount"]], "1200.00")
        self.assertEqual(clean[0].row[self.heal.COL["Currency"]], "USD")
        self.assertTrue(any(change.column_affected == "Currency" for change in changelog))

    def test_notes_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["All expenses above were approved by John Manager on Jan 15 after manual SAP review", "", "", "", "", "", "", ""],
        ]

        clean, quarantine, _ = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 0)
        self.assertEqual(quarantine[0].reason, "Appears to be a notes row")

    def test_calculated_subtotal_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "Finance", "2023-01-16", "200.00", "USD", "Travel", "Approved", "Hotel"],
            ["TOTAL", "", "", "300.00", "", "", "", ""],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 2)
        self.assertEqual(quarantine[0].reason, "Calculated subtotal row")
        self.assertTrue(any(change.reason == "Calculated subtotal row" for change in changelog))

    def test_merged_cell_style_blanks_are_forward_filled(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "", "2023-01-16", "150.00", "USD", "Travel", "Approved", "Hotel"],
            ["Katherine Johnson", "", "2023-01-17", "175.00", "USD", "Travel", "Approved", "Meal"],
            ["Alan Turing", "HR", "2023-01-18", "200.00", "USD", "Training", "Approved", "Workshop"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[1].row[self.heal.COL["Department"]], "Finance")
        self.assertEqual(clean[2].row[self.heal.COL["Department"]], "Finance")
        self.assertTrue(any("merged-cell style export gap" in change.reason for change in changelog))

    def test_semantic_mode_normalises_alternate_headers(self):
        rows = [
            ["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"],
            ["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "travel", "approved", "Taxi ride"],
            ["grace hopper", "finance", "2023-01-16T00:00:00Z", "", "EUR 99.5", "meals", "pending review", "Client lunch"],
        ]

        clean, quarantine, changelog, headers, mode = self.heal.process_generic(rows, ",")

        self.assertEqual(mode, "semantic")
        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[0].row[0], "Ada Lovelace")
        self.assertEqual(clean[0].row[1], "Finance")
        self.assertEqual(clean[0].row[2], "2023-01-15")
        self.assertEqual(clean[0].row[3], "1200.00")
        self.assertEqual(clean[0].row[4], "USD")
        self.assertEqual(clean[0].row[5], "Travel")
        self.assertEqual(clean[0].row[6], "Approved")
        self.assertEqual(clean[1].row[3], "99.50")
        self.assertEqual(clean[1].row[4], "EUR")
        self.assertEqual(clean[1].row[6], "Pending")
        self.assertTrue(any(change.column_affected == "Curr" for change in changelog))

    def test_semantic_mode_forward_fills_department_like_columns(self):
        rows = [
            ["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"],
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "", "2023-01-16", "150.00", "USD", "Travel", "Approved", "Hotel"],
            ["Katherine Johnson", "", "2023-01-17", "175.00", "USD", "Travel", "Approved", "Meal"],
            ["Alan Turing", "HR", "2023-01-18", "200.00", "USD", "Training", "Approved", "Workshop"],
        ]

        clean, quarantine, changelog, headers, mode = self.heal.process_generic(rows, ",")

        self.assertEqual(mode, "semantic")
        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[1].row[1], "Finance")
        self.assertEqual(clean[2].row[1], "Finance")
        self.assertTrue(any(change.column_affected == "Division" for change in changelog))

    def test_read_file_accepts_explicit_sheet_name_for_multisheet_workbooks(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "multi.xlsx"
            wb = Workbook()
            ws1 = wb.active
            ws1.title = "Primary"
            ws1.append(["name", "score"])
            ws1.append(["Ada", 10])
            ws2 = wb.create_sheet("Backup")
            ws2.append(["name", "score"])
            ws2.append(["Grace", 11])
            wb.save(path)

            rows, delimiter = self.heal.read_file(path, sheet_name="Backup")

            self.assertEqual(delimiter, ",")
            self.assertEqual(rows[0], ["name", "score"])
            self.assertEqual(rows[1], ["Grace", "11"])

    def test_parse_args_supports_all_sheets_flag(self):
        args = self.heal.parse_args(["input.xlsx", "output.xlsx", "--all-sheets"])

        self.assertEqual(args.input, "input.xlsx")
        self.assertEqual(args.output, "output.xlsx")
        self.assertTrue(args.all_sheets)
        self.assertIsNone(args.sheet_name)

    def test_read_file_can_consolidate_multisheet_workbooks(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "multi.xlsx"
            wb = Workbook()
            ws1 = wb.active
            ws1.title = "Q1"
            ws1.append(["name", "score"])
            ws1.append(["Ada", 10])
            ws2 = wb.create_sheet("Q2")
            ws2.append(["name", "score"])
            ws2.append(["Grace", 11])
            wb.save(path)

            rows, delimiter = self.heal.read_file(path, consolidate_sheets=True)

            self.assertEqual(delimiter, ",")
            self.assertEqual(rows[0], ["name", "score"])
        self.assertEqual(rows[1], ["Ada", "10"])
        self.assertEqual(rows[2], ["Grace", "11"])

    def test_parse_role_overrides_accepts_valid_mapping(self):
        overrides = self.heal.parse_role_overrides(["1=name", "4=amount", "8=ignore"])
        self.assertEqual(overrides, {0: "name", 3: "amount", 7: "ignore"})

    def test_read_file_preserves_workbook_preamble_rows(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "preamble.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Transactions"
            ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
            ws.append(["Generated by SAP on 15/01/2024", "", "", "", "", "", "", ""])
            ws.append(["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"])
            ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "travel", "approved", "Taxi"])
            wb.save(path)

            rows, delimiter = self.heal.read_file(path, sheet_name="Transactions")

            self.assertEqual(delimiter, ",")
            self.assertEqual(rows[0][0], "Employee Expense Report - Q3 2023")
            self.assertEqual(rows[1][0], "Generated by SAP on 15/01/2024")
            self.assertEqual(rows[2][0], "Emp Name")

    def test_execute_healing_semantic_mode_on_workbook_with_preamble(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "semantic_workbook.xlsx"
            output_path = Path(tmpdir) / "semantic_workbook_healed.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Transactions"
            ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
            ws.append(["Generated by SAP on 15/01/2024", "", "", "", "", "", "", ""])
            ws.append(["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"])
            ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "travel", "approved", "Taxi"])
            ws.append(["grace hopper", "", "2023-01-16T00:00:00Z", "", "EUR 99.5", "meals", "pending review", "Client lunch"])
            ws.append(["alan turing", "hr", "01/17/2023", "200", "usd", "training", "approved", "Workshop"])
            wb.save(path)

            result = self.heal.execute_healing(path, sheet_name="Transactions")
            self.heal.write_workbook(
                result["clean_data"],
                result["quarantine"],
                result["changelog"],
                output_path,
                headers=result["headers"],
            )

            self.assertEqual(result["mode"], "semantic")
            self.assertEqual(len(result["quarantine"]), 0)
            self.assertEqual(result["clean_data"][0].row[0], "Ada Lovelace")
            self.assertEqual(result["clean_data"][0].row[2], "2023-01-15")
            self.assertEqual(result["clean_data"][0].row[3], "1200.00")
            self.assertEqual(result["clean_data"][0].row[4], "USD")
            self.assertEqual(result["clean_data"][1].row[1], "Finance")
            self.assertEqual(result["clean_data"][1].row[3], "99.50")
            self.assertEqual(result["clean_data"][1].row[4], "EUR")
            self.assertTrue(output_path.exists())
            self.assertTrue(any("File Metadata" in change.reason for change in result["changelog"]))

    def test_execute_healing_semantic_mode_on_workbook_with_stacked_headers(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "stacked_header_workbook.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Transactions"
            ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
            ws.append(["Employee", "", "Transaction", "", "", "Approval", "", ""])
            ws.append(["Name", "Division", "Date", "Cost", "Curr", "State", "Comments", ""])
            ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "approved", "Taxi", ""])
            ws.append(["grace hopper", "", "2023-01-16T00:00:00Z", "", "EUR 99.5", "pending review", "Client lunch", ""])
            wb.save(path)

            result = self.heal.execute_healing(path, sheet_name="Transactions")

            self.assertEqual(result["mode"], "semantic")
            self.assertEqual(result["headers"][0], "Employee Name")
            self.assertEqual(result["headers"][2], "Transaction Date")
            self.assertEqual(result["clean_data"][0].row[0], "Ada Lovelace")
            self.assertEqual(result["clean_data"][0].row[2], "2023-01-15")
            self.assertEqual(result["clean_data"][0].row[3], "1200.00")
            self.assertEqual(result["clean_data"][0].row[4], "USD")
            self.assertEqual(result["clean_data"][1].row[1], "Finance")
            self.assertEqual(result["clean_data"][1].row[4], "EUR")
            self.assertTrue(any(change.column_affected == "[header band]" for change in result["changelog"]))

    def test_inspect_healing_plan_reports_header_band_and_semantic_columns(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "inspect_workbook.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Transactions"
            ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
            ws.append(["Employee", "", "Transaction", "", "", "Approval", "", ""])
            ws.append(["Name", "Division", "Date", "Cost", "Curr", "State", "Comments", ""])
            ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "approved", "Taxi", ""])
            wb.save(path)

            inspection = self.heal.inspect_healing_plan(path, sheet_name="Transactions")

            self.assertEqual(inspection["healing_mode_candidate"], "semantic")
            self.assertEqual(inspection["metadata_rows_removed"], 1)
            self.assertTrue(inspection["header_band_merged"])
            self.assertEqual(inspection["detected_header_band_rows"], [2, 3])
            self.assertEqual(inspection["effective_headers"][0], "Employee Name")
            roles = {entry["header"]: entry["role"] for entry in inspection["semantic_columns"]}
            self.assertEqual(roles["Employee Name"], "name")
            self.assertEqual(roles["Transaction Date"], "date")

    def test_inspect_healing_plan_honours_role_overrides(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "override_workbook.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Transactions"
            ws.append(["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Approval State", "Comments"])
            ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "approved", "Taxi"])
            wb.save(path)

            inspection = self.heal.inspect_healing_plan(
                path,
                sheet_name="Transactions",
                role_overrides={1: "category"},
            )

            applied = {int(k): v for k, v in inspection["applied_role_overrides"].items()}
            self.assertEqual(applied[2], "category")
            roles = {entry["column_index"]: entry["role"] for entry in inspection["semantic_columns"]}
            self.assertEqual(roles[2], "category")
            comparison = {entry["column_index"]: entry for entry in inspection["semantic_comparison"]}
            self.assertEqual(comparison[2]["override_role"], "category")
            self.assertEqual(comparison[2]["final_role"], "category")
            self.assertEqual(comparison[1]["detected_role"], "name")

    def test_execute_healing_handles_ragged_clinical_layout(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "clinical_ragged.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Ward Report"
            ws.append(["Clinical Summary", "", "", "", "", "", "", "", "", ""])
            ws.append(["", "", "Patient", "", "Visit", "", "Charge", "", "Billing", ""])
            ws.append(["", "", "Name", "Ward", "Date", "Type", "Amount", "Currency", "Status", ""])
            ws.append(["", "", "alice wong", "Ward A", "15/01/2023", "Consult", "$125.00", "", "approved", ""])
            ws.append(["", "", "bob li", "", "2023-01-16", "Lab", "", "USD 88", "pending review", ""])
            wb.save(path)

            inspection = self.heal.inspect_healing_plan(path, sheet_name="Ward Report")
            result = self.heal.execute_healing(path, sheet_name="Ward Report")

            self.assertEqual(inspection["healing_mode_candidate"], "semantic")
            self.assertEqual(inspection["effective_headers"][0], "Patient Name")
            self.assertEqual(result["mode"], "semantic")
            self.assertEqual(result["clean_data"][0].row[0], "Alice Wong")
            self.assertEqual(result["clean_data"][0].row[2], "2023-01-15")
            self.assertEqual(result["clean_data"][0].row[4], "125.00")
            self.assertEqual(result["clean_data"][0].row[5], "USD")
            self.assertEqual(result["clean_data"][1].row[1], "Ward A")
            self.assertEqual(result["clean_data"][1].row[4], "88.00")
            self.assertEqual(result["clean_data"][1].row[5], "USD")

    def test_execute_healing_semantic_mode_without_amount_column(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "clinical_status.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Clinical Log"
            ws.append(["Hospital Census Export", "", "", "", "", "", "", ""])
            ws.append(["", "", "Patient", "", "Visit", "", "Review", ""])
            ws.append(["", "", "", "", "Encounter", "", "Disposition", ""])
            ws.append(["", "", "Name", "Ward", "Date", "Clinic", "Status", "Notes"])
            ws.append(["", "", "jane doe", "Ward B", "2023/01/15", "North Wing", "pending review", "needs callback"])
            ws.append(["", "", "john smith", "", "15-01-2023", "North Wing", "approved", "seen by nurse"])
            wb.save(path)

            inspection = self.heal.inspect_healing_plan(path, sheet_name="Clinical Log")
            result = self.heal.execute_healing(path, sheet_name="Clinical Log")

            self.assertEqual(inspection["healing_mode_candidate"], "semantic")
            self.assertEqual(inspection["detected_header_band_rows"], [2, 3, 4])
            self.assertEqual(result["mode"], "semantic")
            self.assertEqual(result["clean_data"][0].row[0], "Jane Doe")
            self.assertEqual(result["clean_data"][0].row[2], "2023-01-15")
            self.assertEqual(result["clean_data"][0].row[4], "Pending")
            self.assertEqual(result["clean_data"][1].row[1], "Ward B")
            self.assertEqual(result["clean_data"][1].row[2], "2023-01-15")
            self.assertEqual(result["clean_data"][1].row[4], "Approved")

    def test_execute_healing_semantic_mode_on_stacked_report_without_amount(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "stacked_report.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Ops"
            ws.append(["Operations Snapshot", "", "", "", "", "", "", ""])
            ws.append(["Employee", "", "Visit", "", "Review", "", "", ""])
            ws.append(["", "", "Encounter", "", "Disposition", "", "", ""])
            ws.append(["Name", "Unit", "Date", "Clinic", "Status", "Notes", "", ""])
            ws.append(["amy pond", "Ward C", "2023-01-18", "East Wing", "approved", "discharged", "", ""])
            wb.save(path)

            inspection = self.heal.inspect_healing_plan(path, sheet_name="Ops")
            result = self.heal.execute_healing(path, sheet_name="Ops")

            roles = {entry["header"]: entry["role"] for entry in inspection["semantic_columns"]}
            self.assertEqual(roles["Employee Name"], "name")
            self.assertEqual(roles["Employee Unit"], "department")
            self.assertEqual(result["mode"], "semantic")
            self.assertEqual(result["clean_data"][0].row[0], "Amy Pond")
            self.assertEqual(result["clean_data"][0].row[1], "Ward C")
            self.assertEqual(result["clean_data"][0].row[2], "2023-01-18")
            self.assertEqual(result["clean_data"][0].row[4], "Approved")


if __name__ == "__main__":
    unittest.main()
