import importlib.util
import sys
import unittest
from pathlib import Path


REPO_ROOT = Path("/Users/razzo/Documents/For Codex/sheet-doctor")
HEAL_PATH = REPO_ROOT / "skills" / "csv-doctor" / "scripts" / "heal.py"


def load_module(path: Path, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


class HealEdgeCaseTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.heal = load_module(HEAL_PATH, "sheet_doctor_heal_edge_cases")

    def test_preprocess_rows_uses_last_header_like_row_and_logs_metadata(self):
        rows = [
            ["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""],
            ["Generated by SAP on 15/01/2024", "", "", "", "", "", "", ""],
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
        ]

        trimmed, changes = self.heal.preprocess_rows(rows)

        self.assertEqual(trimmed[0], self.heal.HEADERS)
        self.assertEqual(len(changes), 2)
        self.assertTrue(all(change.column_affected == "[file metadata]" for change in changes))

    def test_formula_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "=SUM(A1:A10)", "USD", "Travel", "Approved", "Carry-over"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 0)
        self.assertEqual(len(quarantine), 1)
        self.assertEqual(quarantine[0].reason, "Excel formula found, not data")
        self.assertTrue(any("formula_residue" in change.reason for change in changelog))

    def test_combined_amount_currency_is_split(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "$1,200 USD", "", "Travel", "Approved", "Taxi"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[0].row[self.heal.COL["Amount"]], "1200.00")
        self.assertEqual(clean[0].row[self.heal.COL["Currency"]], "USD")
        self.assertTrue(any(change.column_affected == "Currency" for change in changelog))

    def test_notes_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["All expenses above were approved by John Manager on Jan 15 after manual SAP review", "", "", "", "", "", "", ""],
        ]

        clean, quarantine, _ = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 0)
        self.assertEqual(quarantine[0].reason, "Appears to be a notes row")

    def test_calculated_subtotal_rows_are_quarantined(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "Finance", "2023-01-16", "200.00", "USD", "Travel", "Approved", "Hotel"],
            ["TOTAL", "", "", "300.00", "", "", "", ""],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(clean), 2)
        self.assertEqual(quarantine[0].reason, "Calculated subtotal row")
        self.assertTrue(any(change.reason == "Calculated subtotal row" for change in changelog))

    def test_merged_cell_style_blanks_are_forward_filled(self):
        rows = [
            self.heal.HEADERS,
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "", "2023-01-16", "150.00", "USD", "Travel", "Approved", "Hotel"],
            ["Katherine Johnson", "", "2023-01-17", "175.00", "USD", "Travel", "Approved", "Meal"],
            ["Alan Turing", "HR", "2023-01-18", "200.00", "USD", "Training", "Approved", "Workshop"],
        ]

        clean, quarantine, changelog = self.heal.process_schema_specific(rows)

        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[1].row[self.heal.COL["Department"]], "Finance")
        self.assertEqual(clean[2].row[self.heal.COL["Department"]], "Finance")
        self.assertTrue(any("merged-cell style export gap" in change.reason for change in changelog))

    def test_semantic_mode_normalises_alternate_headers(self):
        rows = [
            ["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"],
            ["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "travel", "approved", "Taxi ride"],
            ["grace hopper", "finance", "2023-01-16T00:00:00Z", "", "EUR 99.5", "meals", "pending review", "Client lunch"],
        ]

        clean, quarantine, changelog, headers, mode = self.heal.process_generic(rows, ",")

        self.assertEqual(mode, "semantic")
        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[0].row[0], "Ada Lovelace")
        self.assertEqual(clean[0].row[1], "Finance")
        self.assertEqual(clean[0].row[2], "2023-01-15")
        self.assertEqual(clean[0].row[3], "1200.00")
        self.assertEqual(clean[0].row[4], "USD")
        self.assertEqual(clean[0].row[5], "Travel")
        self.assertEqual(clean[0].row[6], "Approved")
        self.assertEqual(clean[1].row[3], "99.50")
        self.assertEqual(clean[1].row[4], "EUR")
        self.assertEqual(clean[1].row[6], "Pending")
        self.assertTrue(any(change.column_affected == "Curr" for change in changelog))

    def test_semantic_mode_forward_fills_department_like_columns(self):
        rows = [
            ["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"],
            ["Ada Lovelace", "Finance", "2023-01-15", "100.00", "USD", "Travel", "Approved", "Taxi"],
            ["Grace Hopper", "", "2023-01-16", "150.00", "USD", "Travel", "Approved", "Hotel"],
            ["Katherine Johnson", "", "2023-01-17", "175.00", "USD", "Travel", "Approved", "Meal"],
            ["Alan Turing", "HR", "2023-01-18", "200.00", "USD", "Training", "Approved", "Workshop"],
        ]

        clean, quarantine, changelog, headers, mode = self.heal.process_generic(rows, ",")

        self.assertEqual(mode, "semantic")
        self.assertEqual(len(quarantine), 0)
        self.assertEqual(clean[1].row[1], "Finance")
        self.assertEqual(clean[2].row[1], "Finance")
        self.assertTrue(any(change.column_affected == "Division" for change in changelog))


if __name__ == "__main__":
    unittest.main()
