from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pandas as pd
from openpyxl import Workbook


ROOT = Path(__file__).resolve().parent
LOADER_DIR = ROOT / "loader"
WORKBOOK_DIR = ROOT / "workbooks"


def ensure_dirs() -> None:
    LOADER_DIR.mkdir(parents=True, exist_ok=True)
    WORKBOOK_DIR.mkdir(parents=True, exist_ok=True)


def write_text_fixtures() -> None:
    (LOADER_DIR / "semicolon_people.csv").write_text(
        "name;amount;currency\nAda;1200,00;EUR\nGrace;88,50;EUR\n",
        encoding="utf-8",
    )
    (LOADER_DIR / "sample.tsv").write_text(
        "name\tscore\tstatus\nAda\t10\tactive\nGrace\t11\tinactive\n",
        encoding="utf-8",
    )
    (LOADER_DIR / "header_only.csv").write_text(
        "name,amount,status\n",
        encoding="utf-8",
    )
    (LOADER_DIR / "empty.csv").write_text("", encoding="utf-8")
    (LOADER_DIR / "records.json").write_text(
        json.dumps(
            [
                {"employee": "Ada", "date": "2024-01-01", "amount": "$12.50", "status": "approved"},
                {"employee": "Ben", "date": "2024/02/03", "amount": "15 EUR", "status": "Pending"},
            ],
            indent=2,
        ),
        encoding="utf-8",
    )
    (LOADER_DIR / "nested_records.json").write_text(
        json.dumps(
            {
                "meta": {"source": "fixture"},
                "rows": [
                    {"name": "Ada", "city": "London"},
                    {"name": "Grace", "city": "New York"},
                ],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (LOADER_DIR / "records.jsonl").write_text(
        "\n".join(
            [
                json.dumps({"employee": "Cara", "date": "2024-03-04", "amount": "99.00", "status": "approved"}),
                json.dumps({"employee": "Dan", "date": "March 5 2024", "amount": "€120,00", "status": "Rejected"}),
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (LOADER_DIR / "corrupt.xls").write_bytes(b"not-a-real-xls")


def write_workbook_fixtures() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Visible"
    ws.append(["name", "score"])
    ws.append(["Ada", 10])
    ws.append(["Grace", 11])
    ws.append(["Linus", 12])
    ws.append(["Margaret", 13])
    hidden = wb.create_sheet("Hidden")
    hidden.sheet_state = "hidden"
    hidden.append(["name", "score"])
    hidden.append(["Hedy", 9])
    very_hidden = wb.create_sheet("VeryHidden")
    very_hidden.sheet_state = "veryHidden"
    very_hidden.append(["name", "score"])
    very_hidden.append(["Katherine", 8])
    wb.save(LOADER_DIR / "multisheet.xlsx")
    wb.save(LOADER_DIR / "multisheet.xlsm")

    ods_path = LOADER_DIR / "multisheet.ods"
    with pd.ExcelWriter(ods_path, engine="odf") as writer:
        pd.DataFrame({"name": ["Ada", "Grace"], "score": [10, 11]}).to_excel(writer, sheet_name="Visible", index=False)
        pd.DataFrame({"name": ["Hedy"], "score": [9]}).to_excel(writer, sheet_name="Hidden", index=False)
        pd.DataFrame({"name": ["Katherine"], "score": [8]}).to_excel(writer, sheet_name="VeryHidden", index=False)

    corrupt_xlsx = LOADER_DIR / "corrupt.xlsx"
    corrupt_xlsx.write_bytes(b"not-a-real-xlsx")

    encrypted_xlsx = LOADER_DIR / "encrypted.xlsx"
    with zipfile.ZipFile(encrypted_xlsx, "w") as archive:
        archive.writestr("EncryptionInfo", b"fake-encryption-info")
        archive.writestr("EncryptedPackage", b"fake-encrypted-package")

    preamble = Workbook()
    ws = preamble.active
    ws.title = "Transactions"
    ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
    ws.append(["Generated by SAP on 15/01/2024", "", "", "", "", "", "", ""])
    ws.append(["Emp Name", "Division", "Txn Date", "Cost", "Curr", "Expense Type", "Approval State", "Comments"])
    ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "travel", "approved", "Taxi"])
    preamble.save(WORKBOOK_DIR / "preamble_workbook.xlsx")

    stacked = Workbook()
    ws = stacked.active
    ws.title = "Transactions"
    ws.append(["Employee Expense Report - Q3 2023", "", "", "", "", "", "", ""])
    ws.append(["Employee", "", "Transaction", "", "", "Approval", "", ""])
    ws.append(["Name", "Division", "Date", "Cost", "Curr", "State", "Comments", ""])
    ws.append(["ada lovelace", "finance", "15/01/2023", "$1,200 USD", "", "approved", "Taxi", ""])
    ws.append(["grace hopper", "", "2023-01-16T00:00:00Z", "", "EUR 99.5", "pending review", "Client lunch", ""])
    stacked.save(WORKBOOK_DIR / "stacked_headers_workbook.xlsx")

    ragged = Workbook()
    ws = ragged.active
    ws.title = "Ward Report"
    ws.append(["Clinical Summary", "", "", "", "", "", "", "", "", ""])
    ws.append(["", "", "Patient", "", "Visit", "", "Charge", "", "Billing", ""])
    ws.append(["", "", "Name", "Ward", "Date", "Type", "Amount", "Currency", "Status", ""])
    ws.append(["", "", "alice wong", "Ward A", "15/01/2023", "Consult", "$125.00", "", "approved", ""])
    ws.append(["", "", "bob li", "", "2023-01-16", "Lab", "", "USD 88", "pending review", ""])
    ragged.save(WORKBOOK_DIR / "ragged_workbook.xlsx")


def main() -> None:
    ensure_dirs()
    write_text_fixtures()
    write_workbook_fixtures()


if __name__ == "__main__":
    main()
