from pathlib import Path

from openpyxl import Workbook

FIXTURE_DIR = Path(__file__).resolve().parent / "excel"
FIXTURE_DIR.mkdir(parents=True, exist_ok=True)


def hidden_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Visible"
    ws.append(["id", "name"])
    ws.append([1, "Ada"])
    hidden = wb.create_sheet("Hidden")
    hidden.sheet_state = "hidden"
    hidden.append(["id", "name"])
    hidden.append([2, "Grace"])
    very_hidden = wb.create_sheet("VeryHidden")
    very_hidden.sheet_state = "veryHidden"
    very_hidden.append(["id", "name"])
    very_hidden.append([3, "Katherine"])
    wb.save(FIXTURE_DIR / "hidden_layers.xlsx")


def stacked_header_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    ws.append(["Quarterly Performance Export", "", "", "", ""])
    ws.append(["Generated by ERP", "", "", "", ""])
    ws.append(["Employee", "Employee", "Transaction", "Review", ""])
    ws.append(["ID", "Name", "Date", "Status", "Notes"])
    ws.append([1001, "Ada Lovelace", "15/01/2024", "approved", "Initial note"])
    ws.append([1002, "Grace Hopper", "2024/02/01", "pending", "Needs follow-up"])
    wb.save(FIXTURE_DIR / "stacked_headers.xlsx")


def preamble_report_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Export"
    ws.append(["Clinical Extract", "", "", ""])
    ws.append(["Generated by EHR on 2024-04-22", "", "", ""])
    ws.append(["patient_id", "patient_name", "visit_date", "status"])
    ws.append(["P-100", "Amina Noor", "2024/04/21", "review"])
    ws.append(["P-101", "Daniel Hart", "21/04/2024", "approved"])
    wb.save(FIXTURE_DIR / "preamble_report.xlsx")


def formula_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Calc"
    ws.append(["item", "amount", "status", "total"])
    ws.append(["A", 10, "ok", "=SUM(B2:B3)"])
    ws.append(["B", 15, "ok", "=B2+B3"])
    ws["B4"] = "#DIV/0!"
    ws["A5"] = "TOTAL"
    ws["B5"] = 25
    wb.save(FIXTURE_DIR / "formula_cases.xlsx")


def merged_and_edges_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Orders"
    ws.append(["", "order_id", "customer", "status", "", ""])
    ws.append(["", 1001, "Ada", "active", "", ""])
    ws.append(["", 1002, None, "active", "", ""])
    ws.append(["", 1003, None, "active", "", ""])
    ws.append(["", None, None, None, "", ""])
    ws.merge_cells("C2:C4")
    ws["C2"] = "Acme Corp"
    wb.save(FIXTURE_DIR / "merged_edges.xlsx")


def text_date_cleanup_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "TextDates"
    ws.append([" note ", "event_date", "status", ""])
    ws.append(["\ufeffSmart “quote”\ntext", "03/04/2024", "APPROVED", ""])
    ws.append(["  extra   spaces  ", "2024/05/06", "pending review", ""])
    ws.append([None, None, None, None])
    wb.save(FIXTURE_DIR / "text_date_cleanup.xlsx")


def duplicate_header_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Dupes"
    ws.append(["customer_id", "customer_id", " amount ", "status"])
    ws.append(["C1", "Ada", 100, "active"])
    ws.append(["C2", "Grace", "N/A", "active"])
    wb.save(FIXTURE_DIR / "duplicate_headers.xlsx")


def notes_totals_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Ledger"
    ws.append(["employee", "amount", "status", "notes"])
    ws.append(["Ada", 100, "approved", ""])
    ws.append(["Grace", 150, "approved", ""])
    ws.append(["All expenses above this row were approved by the regional manager after the monthly review closed.", "", "", ""])
    ws.append(["TOTAL", 250, "", ""])
    wb.save(FIXTURE_DIR / "notes_totals.xlsx")


def ragged_clinical_workbook() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Clinical"
    ws.append(["", "", "Clinical Follow-up Export", "", "", ""])
    ws.append(["", "", "Generated by System", "", "", ""])
    ws.append(["", "Patient", "Patient", "Visit", "Review", ""])
    ws.append(["", "ID", "Ward", "Date", "Status", ""])
    ws.append(["", "P-100", "Ward A", "2024/06/01", "pending", ""])
    ws.append(["", "P-101", None, "01/06/2024", "approved", ""])
    ws.append(["", None, None, None, None, ""])
    wb.save(FIXTURE_DIR / "ragged_clinical.xlsx")


if __name__ == "__main__":
    hidden_workbook()
    stacked_header_workbook()
    preamble_report_workbook()
    formula_workbook()
    merged_and_edges_workbook()
    text_date_cleanup_workbook()
    duplicate_header_workbook()
    notes_totals_workbook()
    ragged_clinical_workbook()
    print(f"Wrote fixtures to {FIXTURE_DIR}")
